[project]
name = "datascience-workflow-on-gpu-cudf"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "aiohttp>=3.14.3",
    "cudf-cu13>=26.8.0",
    "cudf-polars-cu13>=26.8.0",
    "jupyter>=1.1.1",
    "pandas>=3.0.3",
    "pip>=26.2.1",
    "plotly>=6.9.0",
    "polars>=1.35,<1.43",
]
